
import { Inter } from "next/font/google";
import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
import AuthProvider from "./components/authProviders/AuthProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Farmers-Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        {children}
        </AuthProvider> 
        </body>
    </html>
    
    
  );
}
