import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kisaan24",
  description: "Generated by Puneeeeeeet",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
