import { Inter } from "next/font/google";
import "./globals.css";
import {NextAuthProvider} from './Providers'
import Nav from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Farmers-Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
      <html lang="en">
      <body className={inter.className}>
      
        <NextAuthProvider>
          {children}      
        
        
        </NextAuthProvider> 
        </body>
    </html>
    
    
  );
}
